### ISSUE TITLE
Question about experiment

### ISSUE THREAD

**Issue by minjoong507** [haojc/ShufflingVideosForTSG#3]
Thanks for sharing your great work!

I have some questions about the experiment. 

1. This paper adopted R@n, IoU@m, mIoU as evaluation. Why not use dR@n, IoU@m metric [1] for evaluation?

2. Have you compared [2, 3] with your work?

[1] A Closer Look at Temporal Sentence Grounding in Videos: Dataset and Metric, arXiv 2021
[2] Towards Debiasing Temporal Sentence Grounding in Video, arXiv 2021
[3] Self-supervised Learning for Semi-supervised Temporal Language Grounding, arXiv 2021

**Comment by haojc** [comment]
Thanks for your focus on our work.
Problem 1 about dR@n, IoU@m: 
We first appreciate the work by [1] to discuss the shortcomings of R@n under small IoU thresholds and their contributions to the re-divided splits. But in our opinion, we don't think dR@n is a better alternative. For example, as shown in Figure 6 in [1], we think that the grounding performance of Prediction 2 is better than Prediction 1, because Pred 2 covers the total gt moment and Pred 1 only overlaps a part. But under the evaluation of dR@n, Pred 1 is better.
![微信截图_20221004162425](https://user-images.githubusercontent.com/30310473/193771467-48866b5d-9f66-4ba8-8a94-7bdd3925e855.png)

We admit that, as pointed out by [1], many predictions such as taking the total video as predictions may lead to a misleading result under small IoU thresholds. But mIoU is a good metric as complementary to evaluate the global grounding performance. So we adopt the original R@n, IoU@m and mIoU as evaluation.

Problem 2 about comparison with [2] and [3]:
Actually, we had noticed the work [2] and we were supervised that this work shows  VSLNet can achieve such good performance on the re-divided splits. Then we tried to reproduce the result using their open-source code but we failed. (We noticed they applied transformer as their encoders and tried to use the finetuned visual feature on Charades). As we don't know which features and detailed models they use, we only compare our method with the original VSLNet[2020] with the same input features as us and their open-source code in our paper.
We haven't compared with [3], because we mainly compared with the strong-supervised works. We find that [3] uses C3D features on both datasets while we use I3D, so we cannot directly compare the scores proposed in the papers.

**Comment by minjoong507** [comment]
Hi, thank you for your kind reply!

I have another question. I think that the proposed framework is agnostic to the grounding model. 

Have you checked the performance using other baseline models?

**Comment by haojc** [comment]
Yes, we have successfully applied our framework to LG(regression-based) and VSLNet(another span-based) and we are attempting the proposal-based models.

**Comment by minjoong507** [comment]
Thanks a lot for your quick response :)

My concerns are clearly addressed in the above answers!

**Comment by haojc** [comment]
You are welcome. Please feel free to contact me if you have any other problems.
