### ISSUE TITLE
Questions about your code

### ISSUE THREAD

**Issue by TikaToka** [haojc/ShufflingVideosForTSG#4]
Hello @haojc, Thank you for sharing great work and code!

While I was looking at your code, there was a point that I could not understand

In your work, there should be a code for creating pseudo video (shuffled video)

The code for this part is the file 'data_augment.py' in [dataset](https://github.com/haojc/ShufflingVideosForTSG/tree/main/grounding/dataset)?

Thank you in advance!

**Comment by haojc** [comment]
Hi, tiktoka. The shuffle code is 'gt_moment_translate' part of data_augment.py. In our implementation, we shuffle videos directly on the feature level. Specifically, we translate randomly the features within target moments to another temporal position. It is mainly because we extract the frame feature with the same stride and fps.  Each frame feature represents the visual content within 1 second and there is nearly no temporal overlap among features. For example, for a video spanning 10s, the length of features will be 10 or 20 ( 1 frame represents 0.5s).  Thus, the impact of shuffling on features is equal to videos.

**Comment by TikaToka** [comment]
Sorry for late reply and Thank you for answer! For now, I will close the issue and I would reopen if I have further questions related to shuffling frames. Thank you again!
