### ISSUE TITLE
Link to dataset features  

### ISSUE THREAD

**Issue by ZhenZHAO** [haojc/ShufflingVideosForTSG#5]
Hi Jiachang,

Thanks for your work and code. I am trying to run your work.

It seems all the provided links (to the features and the word embedding of ActivityNet) are not available now. Can you please help to fix it?

Bests,

Zhen

**Comment by haojc** [comment]
Hi, Zhen. I don't know why the original box drive link didn't work recently. I have updated the link to these files. And the new link works well. You can try it now.

**Comment by ZhenZHAO** [comment]
Hi jiachang, appreciate your quick reply. 
Have your update the link??  it seems the current link provided in the REAMDE still does not work.  
- https://app.box.com/s/nruly3nocdzid9atm78n12i7jbvu8bh4

**Comment by haojc** [comment]
Yes, it's the updated link. We tested it just now. And I can open the site. I will let other people try again.

**Comment by haojc** [comment]
Hi, Zhen. The link can be connected but unstable, and the download speed is slow. So I will change the cloud platform and add a download link for Chinese mainland researchers. After I finished, I will inform you here.

**Comment by haojc** [comment]
Hi, Zhen. I have updated the links of google and baidu drives. You can try it again. Please feel free to contact me if you have any other problems.
By the way, I read your [project](https://github.com/ZhenZHAO/awesome-video-moment-retrieval) to summarize the methods for temporal sentence grounding. I very like it because it is the most comprehensive and detailed summary job I have seen. Can I add your Wechat for convenient communication in the further？If you agree it, you can send your wechat id to my email (haojc@bupt.edu.cn).
